name = "ExamplePkg"
uuid = "210e419a-0a9f-472d-927f-6eff903495ba"
authors = ["Eric Ford <ebf11@psu.edu>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
PlutoLinks = "0ff47ea0-7a50-410d-8455-4348d5de0420"
PlutoTest = "cb4044da-4d16-4ffa-a6a3-8cad7f73ebdc"

[compat]
Pkg = "1.11.0"
Pluto = "0.20.17"
julia = "1.11"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
build = ["Pkg", "Pluto"]
test = ["Pluto", "Pkg", "Random", "Test"]
